spring.application.name=lendit-backend

# Server
server.port=8080

# AIVEN_MySQL
spring.datasource.url=jdbc:mysql://mysql-2ef765a4-lendit.d.aivencloud.com:17008/defaultdb?sslMode=VERIFY_CA&trustCertificateKeyStoreUrl=file:C:/Users/chand/Downloads/ca.pem
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_t3BORNcgVaqs2rNXURN
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=LendItSecretKey2026SuperSecureRandomStringForJWTSigning
jwt.expiration=86400000

# File Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
file.upload-dir=uploads
